### ISSUE TITLE
Anti-Xray not working?

### ISSUE THREAD

**Issue by BetaTester41** [the-glitch-network/plymouth-fabric#22]
### What module(s) is this issue related to?

- [X] Anti-Xray `ply-anti-xray`
- [ ] Common `ply-common`
- [ ] Database `ply-database`
- [ ] Locking `ply-locking`
- [ ] Tracker `ply-tracker`
- [ ] Miscallenious `plymouth`
- [ ] Debug `ply-debug`

### Environment

- **Minecraft**: 1.19.2 Server
- **Plymouth**: 0.0.0+mc.1.19.2
- **Mod Loader**: Fabric
- **Java**: GraalVM JDK "17.0.5"

### To reproduce

1. Install the mod on server side
2. Use a client to connect to the server
3. Activate the xray program

### Expected results

Ore locations are not visible 

### Actual results

Ore locations are visible

### Anything else?

I have tested this client side, and the same effect is achieved. I don't know if its something related to third party mods. There are notable lines in the log that describe the following:
![image](https://user-images.githubusercontent.com/76068161/227064713-93b42984-c9c1-4ed5-8d60-0cd57056394a.png)
I don't know if it's due to the failed redirects.

**Comment by Ampflower** [comment]
For the server, it could be useful to list what mods you may have installed.

You may also want to check that the `plymouth-anti-xray:hidden` tag is indeed populated; you can check via F3 over ores or various containers that should be hidden.

I should note that the anti-xray has no ability to hide ores exposed to air; it is one of its downsides; however ores and other things that are completely covered on all 6 sides should be hidden; if they are not and they have the tag, that is something to look into, since it means something is not doing its job.

**Comment by BetaTester41** [comment]
Ohh I see what you mean. I have check it out, and indeed it has the tag. I didn't read #16. Seems like the different engines are in the works. Thanks for the help!
